# Generated by Django 4.2 on 2023-05-22 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('list_themes', models.TextField(verbose_name='Список тем')),
                ('about_course', models.TextField(verbose_name='О курсе')),
                ('for_whom', models.TextField(verbose_name='Для кого')),
                ('basic_requirements', models.TextField(verbose_name='Начальные требования')),
                ('course_program', models.TextField(verbose_name='Программа курса')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
